#!/bin/bash
# setup-worktree.sh — Allocate random ports for an isolated dev stack.
#
# Run once in a worktree to generate worktree.env with unique ports.
# All dev scripts source worktree.env so multiple worktrees don't collide.
#
# Usage: scripts/setup-worktree.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/worktree.env"

# --- Helpers ---

find_free_port() {
    python3 -c "import socket; s=socket.socket(); s.bind(('',0)); print(s.getsockname()[1]); s.close()"
}

find_free_adb_port() {
    # ADB ports must be even numbers in 5554-5682
    for port in $(seq 5554 2 5682); do
        if ! ss -tlnp 2>/dev/null | grep -q ":${port} " && \
           ! ss -tlnp 2>/dev/null | grep -q ":$((port + 1)) "; then
            echo "$port"
            return
        fi
    done
    echo "ERROR: No free ADB port in 5554-5682" >&2
    exit 1
}

find_free_display() {
    # Find an X display number not in use (check /tmp/.X*-lock)
    for n in $(seq 50 99); do
        if [ ! -f "/tmp/.X${n}-lock" ]; then
            echo ":${n}"
            return
        fi
    done
    echo "ERROR: No free X display in :50-:99" >&2
    exit 1
}

# --- Check if already set up ---

if [ -f "$ENV_FILE" ]; then
    echo "worktree.env already exists at $ENV_FILE"
    echo "Delete it first to regenerate: rm $ENV_FILE"
    cat "$ENV_FILE"
    exit 0
fi

# --- Detect worktree ---

if [ -f "$PROJECT_ROOT/.git" ]; then
    echo "Detected git worktree"
elif [ -d "$PROJECT_ROOT/.git" ]; then
    echo "Note: This is the main repo, not a worktree. Setting up anyway."
fi

# --- Probe ports ---

echo "Probing free ports..."

CADDY_PORT=$(find_free_port)
TREADMILL_SERVER_PORT=$(find_free_port)
VITE_SERVER_PORT=$(find_free_port)
EMU_ADB_PORT=$(find_free_adb_port)
EMU_DISPLAY=$(find_free_display)
EMU_VNC_PORT=$(find_free_port)
EMU_NOVNC_PORT=$(find_free_port)

# --- Write env file ---

cat > "$ENV_FILE" << EOF
# Generated by setup-worktree.sh — do not edit manually
# Delete and re-run setup-worktree.sh to regenerate

export CADDY_PORT=$CADDY_PORT
export TREADMILL_SERVER_PORT=$TREADMILL_SERVER_PORT
export VITE_SERVER_PORT=$VITE_SERVER_PORT
export EMU_DISPLAY=$EMU_DISPLAY
export EMU_ADB_PORT=$EMU_ADB_PORT
export EMU_VNC_PORT=$EMU_VNC_PORT
export EMU_NOVNC_PORT=$EMU_NOVNC_PORT
EOF

# --- npm install ---

if [ -d "$PROJECT_ROOT/ui" ] && [ -f "$PROJECT_ROOT/ui/package.json" ]; then
    echo ""
    echo "Installing UI dependencies..."
    (cd "$PROJECT_ROOT/ui" && npm install --silent)
fi

# --- Summary ---

echo ""
echo "=== Worktree Environment ==="
echo "  Caddy (entry):    http://localhost:$CADDY_PORT"
echo "  Server (internal): http://localhost:$TREADMILL_SERVER_PORT"
echo "  Vite (internal):   http://localhost:$VITE_SERVER_PORT"
echo "  Emulator display:  $EMU_DISPLAY"
echo "  Emulator ADB:      localhost:$EMU_ADB_PORT"
echo "  Emulator VNC:      localhost:$EMU_VNC_PORT"
echo "  Emulator noVNC:    http://localhost:$EMU_NOVNC_PORT/vnc.html"
echo ""
echo "Written to: $ENV_FILE"
echo ""
echo "Start dev stack:  TREADMILL_MOCK=1 ./scripts/dev.sh"
